version: '3'

networks:
  iam_network:
    name: iam_network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
  
services:
  # Mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123ewq
      - MARIADB_DATABASE=keycloak
      - MARIADB_USER=keycloak
      - MARIADB_PASSWORD=keycloak
    networks:
      - iam_network
    ports:
      - 3306:3306
    restart: always
  
  # Keycloak
  keycloak:
    container_name: keycloak
    build: keycloak-build/.
    image: keycloak:build
    networks:
      - iam_network
    volumes:
      - $PWD/cert/keycloak.local.crt:/etc/x509/https/tls.crt
      - $PWD/cert/keycloak.local.key:/etc/x509/https/tls.key
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
    depends_on:
      - mariadb
    ports:
      - 443:8443
    restart: always