version: '3'

networks:
  iam_network:
    name: iam_network
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - iam_network
    ports:
      - 5432:5432
    restart: always
  
  # Keycloak
  keycloak:
    container_name: keycloak
    build: .
    image: keycloak:build
    networks:
      - iam_network
    volumes:
      - /Users/bachns/workspace/lab/iam/keycloak.local.crt:/etc/x509/https/tls.crt
      - /Users/bachns/workspace/lab/iam/keycloak.local.key:/etc/x509/https/tls.key
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
    depends_on:
      - postgres
    ports:
      - 443:8443
    restart: always